name: jupyter-xchem
channels:
  - plotly
  - conda-forge
dependencies:
  - numpy
  - pandas
  - jupyter
  - plotly
  - plotly-orca
  - scipy
  - psutil
  - requests
  - rdkit
  - openbabel=3.0.0
  - nglview
